-- DROP ROLE IF EXISTS <ROLE>;

-- CREATE ROLE <ROLE> WITH LOGIN PASSWORD <PASSWORD>;

-- GRANT CONNECT ON DATABASE url_shortener_db TO <ROLE>;

-- GRANT INSERT,DELETE,UPDATE,SELECT ON ALL TABLES IN SCHEMA PUBLIC TO <ROLE>;